### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by DevRicardoAndrade** [isp1x3r/Warfare#13]
Brother do this project again it would be great to be able to replay the 2014 version.
Count on me for any help with programming, I'm not that good but I can learn.

**Comment by isp1x3r** [comment]
Hello sir, Thank you for your interest and I am partly working on this one, Though it's mostly a matter of reverse engineering the game client which is quite tedious but you can reach out of to me on discord(un : sp1x3r) and we can further discuss it.
